<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoCompleteTextBox" Version="1.7.3" />
    <PackageReference Include="DotNetProjects.WpfToolkit.Input" Version="6.1.94" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes.Wpf" Version="1.0.1" />
    <PackageReference Include="Syncfusion.Tools.WPF" Version="33.2.4" />
  </ItemGroup>

</Project>
